name: Catalog Service

on:
  push:
    paths:
      - catalog-service/**
    branches:
      - 'main'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      working_directory: ./catalog-service
      DOCKER_IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/bookstore-catalog-service
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
#      - name: Checkout Code
      - uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Generate Maven Wrapper
#        run: mvn -N io.takari:maven:wrapper || true
        run: chmod +x mvnw

      - name: Build with Maven
        run: ./mvnw -ntp verify

# only if the current branch is main that the github action
# can login to dockerhub would be possible build d docker image and push it to docker hub

      - if: ${{ github.ref == 'refs/heads/main' }}
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

#create a docker image and push to docker hub
      - if: ${{ github.ref == 'refs/heads/main' }}
        name: Build and Publish Docker Image
        run:
          ./mvnw spring-boot:build-image -DskipTests
          docker push ${{ secrets.DOCKER_USERNAME }}/bookstore-catalog-service