name: Catalog Service

on:
  push:
    paths:
      - 'catalog-service/**'
    branches:
      - '**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Ensure Maven Wrapper Executability
        run: chmod +x ./catalog-service/mvnw

      - name: Build with Maven
        run: ./catalog-service/mvnw -ntp verify
